### ISSUE TITLE
Intro session?

### ISSUE THREAD

**Issue by RichStone** [curiouscoderscommunity/curious-coders#14]

**Comment by RichStone** [comment]
ideas:

- why did we get this started?
- developer origin story @RichStone and @bouwe77 
- example of a topic from the other Issues here
- picks (?) longterm would be cool to have something more interactive/innovative than picks, but we can start with that?
- what's next

**Comment by bouwe77** [comment]
What is picks?

**Comment by RichStone** [comment]
lots of podcasts have picks, at the end is a round where everyone picks one or more things they liked recently, like a good blog post, anything you are up to, a good movie or board game, piece of music, whatever floats your boat...

**Comment by bouwe77** [comment]
Ah yes of course 👍

**Comment by bouwe77** [comment]
Let's also do some coding, if only for 15 minutes, to make the episode give a better impression of what is coming?

**Comment by RichStone** [comment]
yesss, that'd be nice. Did you have something in mind?

**Comment by RichStone** [comment]
We are not just curious coders but also fascinated by all types of tech, among them the modern frontend stack, right?

Wouldn't it be cool if we use the first 10-15 minutes for the introductions and then in the rest of the session we create and deploy a landing page for curiouscoders.xyz? 🤔

**Comment by bouwe77** [comment]
Yeah also great 😃👍

Let's buid it test-driven in HTML + CSS, and maybe add JS sprinkles, if necessary.

And if course embed our WG channel 😏

As a sneak peak to things we might dive in in more depth later?

**Comment by bouwe77** [comment]
Ah, you said "modern", but for now, YAGNI? 🤷

**Comment by RichStone** [comment]
I'm all for vanilla js (if even needed). VanillaJS is also modern and together with netlify or GitHub hosting it's pretty modern right?

**Comment by bouwe77** [comment]
Agreed 👍

**Comment by bouwe77** [comment]
I think we have to promise ourselves and our viewers we will finish something and put it online.

However, how to prevent it becoming ugly? 

Although I mist say I am more the "get it working first" kinda developer, and am satisfied pretty quickly, however it looks 😂

**Comment by RichStone** [comment]
PROMISE 😬

**Comment by RichStone** [comment]
Yes, I don't think it matters much for the first version. If we like, we can refine, otherwise recode in the next iteration, in episode #108 :D

**Comment by RichStone** [comment]
I mean, it also depends on what we want with it? If it has some user-facing functionality and we will want to share that page, we'll most probably be against leaving it unrefined, in which case we can do it anytime later, right?

**Comment by bouwe77** [comment]
Yeah anything is fine, let's see what we come up with. It can be a nice project to revisit multiple times later and apply/test other topics on it.

**Comment by RichStone** [comment]
https://curiouscoders.webinargeek.com/enter-curious-coders-web-cast
